---
name: media-naming-dev

services:
  media-naming-dev:
    container_name: media-naming-dev
    image: progower/media-naming:dev
    user: 1000:1000
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/usr/src/app:rw
    restart: "no"
